apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-eks-admins-to-cluster-admin
subjects:
- kind: Group
  name: eks-admins # <-- MUST MATCH the name you used in the Access Entry
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin # <-- The powerful built-in K8s role
  apiGroup: rbac.authorization.k8s.io