apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: israel-jenkins
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: israel-jenkins-admin
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "pods/portforward"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods/attach", "pods/proxy", "pods/exec", "pods/bind", "pods/eviction"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["v1"]
  resources: ["services", "configmaps", "secrets", "endpoints"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["extensions", "apps"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
- apiGroups: ["eks.amazonaws.com"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: israel-jenkins-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: israel-jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: israel-jenkins
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: israel-jenkins
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token
