apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
  labels:
    name: jenkins
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: luxe-store-app
  labels:
    name: luxe-store-app
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: luxe-store-argo
  labels:
    name: luxe-store-argo
    env: dev
---
# NetworkPolicy to allow traffic between namespaces
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace-traffic
  namespace: israel-jenkins
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: israel-jenkins
    - namespaceSelector:
        matchLabels:
          name: israel-app
    - namespaceSelector:
        matchLabels:
          name: israel-argo
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: israel-jenkins
    - namespaceSelector:
        matchLabels:
          name: israel-app
    - namespaceSelector:
        matchLabels:
          name: israel-argo
